[project]
authors = ["gkreder <gkreder@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "metabozen"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"
numpy = ">=2.1.2,<3"
pandas = ">=2.2.3,<3"
scipy = ">=1.14.1,<2"
scikit-learn = ">=1.5.2,<2"
matplotlib = ">=3.9.2,<4"
rpy2 = ">=3.5.11,<4"
ipdb = ">=0.13.13,<0.14"
tqdm = ">=4.66.6,<5"
pyyaml = ">=6.0.2,<7"
xlrd = ">=2.0.1,<3"
lxml = ">=5.3.0,<6"
r-base = ">=4.3.3,<5"
r-tidyverse = ">=2.0.0,<3"
sphinx = ">=8.1.3,<9"
sphinx-rtd-theme = ">=3.0.1,<4"
myst-parser = ">=4.0.0,<5"
sphinx-autodoc-typehints = ">=3.0.1,<4"
furo = ">=2024.8.6,<2025"
sphinx-copybutton = ">=0.5.2,<0.6"

[feature.conda-build.dependencies]
conda-build = "*"

[environments]
conda-build = ["conda-build"]

[pypi-dependencies]
pyteomics = ">=4.7.5, <5"
