   name: Build and Test Conda Package

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            include:
              - os: ubuntu-latest
                target-platform: linux-64
              - os: ubuntu-latest
                target-platform: linux-aarch64
              - os: windows-latest
                target-platform: win-64
        steps:
          - uses: actions/checkout@v4
          - name: Build conda package
            uses: prefix-dev/rattler-build-action@v0.2.18
            with:
              artifact-name: package-${{ matrix.target-platform }}
              build-args: --target-platform ${{ matrix.target-platform }}${{ matrix.target-platform == 'linux-aarch64' && ' --no-test' || '' }}
          