   name: Build and Test Conda Package

   defaults:
     run:
       shell: "bash -el {0}"

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            include:
              - os: ubuntu-latest
                target-platform: linux-64
              # - os: ubuntu-latest
                # target-platform: linux-aarch64
              # - os: windows-latest
                # target-platform: win-64
        name: Conda Package Build
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Miniconda
            uses: conda-incubator/setup-miniconda@v3
            with:
              auto-update-conda: true
              channels: conda-forge, bioconda, defaults
              environment-file: environment.yml
              activate-environment: metabozen-env

          - name: Install Conda-Build and Other Dependencies
            run: |
              conda install -y conda-build anaconda-client

          - name: Build the Conda Package
            run: |
              conda build conda/

          - name: Test Installation Locally
            run: |
              conda install --use-local metabozen

          - name: Test Package Import
            run: |
              python -c "import metabozen"

        