   name: Build and Test Conda Package

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: ["ubuntu-latest", "windows-latest"]
        steps:
          - uses: actions/checkout@v4
          - uses: conda-incubator/setup-miniconda@v2
            with:
              python-version: 3.12
          - uses: cascode-labs/build-conda-action/action.yml@v0
            with: 
              recipe_path: conda/meta.yaml