   name: Build and Test Conda Package

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: ["ubuntu-latest", "windows-latest"]
        steps:
          - uses: actions/checkout@v4
          
          - name: Set up Miniconda
            uses: conda-incubator/setup-miniconda@v3
            with:
              auto-update-conda: true
              python-version: 3.12

          - name: Install dependencies
            run: |
              conda config --add channels bioconda
              conda config --add channels conda-forge
              conda config --set channel_priority strict
              conda create -y -n metabozen-env python=3.12 conda-build anaconda-client

          - name: Build package
            run: |
              conda run -n metabozen-env conda build conda/
          
          - name: Verify package build output
            run: ls $(conda info --base)/conda-bld/noarch

          - name: Test package
            run: |
              conda run -n metabozen-env conda config --append channels file://$(conda info --base)/conda-bld
              conda run -n metabozen-env conda install --use-local metabozen
              conda run -n metabozen-env metabozen --help

          - name: Upload build artifacts
            uses: actions/upload-artifact@v4
            with:
              name: metabozen-package
              path: $(conda info --base)/conda-bld/noarch/*.tar.bz2
              # path: /home/runner/miniconda3/conda-bld/noarch/*.tar.bz2


